### ISSUE TITLE
[Issue]: Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by Woisek** [derrian-distro/LoRA_Easy_Training_Scripts#160] opened 2023-11-26 21:11 UTC
Fresh install, and a problem with 'Triton'.
Any idea how to solve this? 🤔

C:\WINDOWS\system32>cd /D "R:\LoRA_Easy_Training_Scripts"
starting validation of args...
starting validation of dataset_args...
T:\AI_training\training\LoRA\EmilyHill_v5\EmilyHill_v5.0.safetensors
validated, starting training...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading settings from runtime_store\config.toml...
Traceback (most recent call last):
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1009, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3297, in read_config_from_file
    config_dict = toml.load(f)
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Reserved escape sequence used (line 24 column 1 char 681)
Failed to train because of error:
Command '['R:\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment] 2023-11-27 01:13
this issue actually has nothing to do with triton, the real issue is because of some escape character that is being used somewhere. This is something that the toml loader has been a constant issue with, and I'm not sure how to fix it, just make sure you don't have miscilaneous '/' or '\\' in your paths, that's all I can suggest tbh

**Comment by Woisek** [comment] 2023-11-27 09:01
Thanks for the reply.

> just make sure you don't have miscilaneous '/' or '\' in your paths, that's all I can suggest tbh

You can see the path in the log, these are just 'normal' paths used by Windows. No added slashs or backslashs. So I'm sure there are no "miscilaneous '/' or '\'" in my paths.
So, more suggestions would be highly appreciated.

**Comment by Jelosus2** [comment] 2023-11-27 14:39
It seems you have the same problem as the user in the issue #152. Also why are you using 100 repeats with 43 images?

**Comment by Woisek** [comment] 2023-11-27 15:20
> Also why are you using 100 repeats with 43 images?

Because I do 1 batch size and only 1 epoch, so 100 should be the minimum of repeats.

**Comment by Woisek** [comment] 2023-11-27 15:22
> I did some research, you could try to activate the venv and use this command `pip install bitsandbytes-windows`

I already tried this, but now I get an error with a missing cuda path that can't be found. I gave up on that one.
A kohya_ss install runs smoother than this repo. There are too many side steps necessary to get it to work, although I would like the interface more.

**Comment by Jelosus2** [comment] 2023-11-28 06:24
> > I did some research, you could try to activate the venv and use this command `pip install bitsandbytes-windows`
> 
> I already tried this, but now I get an error with a missing cuda path that can't be found. I gave up on that one. A kohya_ss install runs smoother than this repo. There are too many side steps necessary to get it to work, although I would like the interface more.

Both trainers use kohya scripts, also it works for me, could i know what GPU are you using?

**Comment by Jelosus2** [comment] 2023-11-28 06:25
> > Also why are you using 100 repeats with 43 images?
> 
> Because I do 1 batch size and only 1 epoch, so 100 should be the minimum of repeats.

A lot of repeats imo, id prefer less repeats and more epochs

**Comment by Woisek** [comment] 2023-11-28 08:28
> Both trainers use kohya scripts, also it works for me, could i know what GPU are you using?

I'm aware of that, that's why my idea of installing bitsandbytes looking at the koya_ss scripts.
I have an Nvidia RTX 2070 SUPER 8GB

**Comment by Jelosus2** [comment] 2023-11-28 13:31
> > Both trainers use kohya scripts, also it works for me, could i know what GPU are you using?
> 
> I'm aware of that, that's why my idea of installing bitsandbytes looking at the koya_ss scripts. I have an Nvidia RTX 2070 SUPER 8GB

I don't see anything wrong at first glance, im using an older version and soon if all goes good ill switch to D8 trainer, but you'll have to wait for derrian to fix it ig

**Comment by Woisek** [comment] 2023-11-28 14:32
What's that D8 trainer?

**Comment by derrian-distro** [comment] 2023-11-28 18:43
> > I did some research, you could try to activate the venv and use this command `pip install bitsandbytes-windows`
> 
> I already tried this, but now I get an error with a missing cuda path that can't be found. I gave up on that one. A kohya_ss install runs smoother than this repo. There are too many side steps necessary to get it to work, although I would like the interface more.

i'm going to be entirely honest, I have never once run into any of these issues, it's hard to help when I can't recreate the issues on my end

**Comment by Woisek** [comment] 2023-11-29 01:08
> i'm going to be entirely honest, I have never once run into any of these issues, it's hard to help when I can't recreate the issues on my end

Thanks, I appreciate this. And I wish I could blame it on ignorance or incompetence on my part, but unfortunately that's not the case.
I have several tools running successfully: A1111/SD:Next, Khoya_ss, ComfyUI and the same in the LLM area, like ooba, SillyTavern kobold.ccp etc.
Everything works, and most of the time right away.
But when I clone the repo again, as I did here, and an error is thrown at me at the very first start because paths are not written correctly in the configuration, then that is very annoying.
Then a component that is apparently important (bitsandbytes) is not included in the requirements, which is also frustrating. But since I already have some experience, I was able to help myself with this step. Others probably can't do that.
If then the cuda path is not found, even though it has already been created umpteen times by the other tools, then that's just bad, I'm sorry to say it that way.
Perhaps the whole installation process should be redeveloped, because I don't think I'm the only one who has experienced this.
I really hope that I can really try out this apparently great tool.

**Comment by Jelosus2** [comment] 2023-11-29 09:41
I think the bitsandbytes issue is when you use AdamW8bit

**Comment by Woisek** [comment] 2023-11-29 13:41
> I think the bitsandbytes issue is when you use AdamW8bit

Even if this would be true, this can't be the answer. Also, if you read, I wrote that bitsandbytes were not installed, I had to install it myself.
After that, the training would have started, but failed to the "missing" cuda path.
So, no, it's not because of the use of AdamW8bit.

**Comment by forrestfunk** [comment] 2023-11-29 22:34
not saying you're wrong, I'm way too unexperienced for that, but I had the exact same issues and errors like you Woisek. After switching to "AdamW" from "AdamW8bit" the tool worked for me.

**Comment by derrian-distro** [comment] 2023-11-30 01:23
> > i'm going to be entirely honest, I have never once run into any of these issues, it's hard to help when I can't recreate the issues on my end
> 
> Thanks, I appreciate this. And I wish I could blame it on ignorance or incompetence on my part, but unfortunately that's not the case. I have several tools running successfully: A1111/SD:Next, Khoya_ss, ComfyUI and the same in the LLM area, like ooba, SillyTavern kobold.ccp etc. Everything works, and most of the time right away. But when I clone the repo again, as I did here, and an error is thrown at me at the very first start because paths are not written correctly in the configuration, then that is very annoying. Then a component that is apparently important (bitsandbytes) is not included in the requirements, which is also frustrating. But since I already have some experience, I was able to help myself with this step. Others probably can't do that. If then the cuda path is not found, even though it has already been created umpteen times by the other tools, then that's just bad, I'm sorry to say it that way. Perhaps the whole installation process should be redeveloped, because I don't think I'm the only one who has experienced this. I really hope that I can really try out this apparently great tool.

I've tested my install script a bunch of times, including while trying to get your issue, and it worked every time. just for the record, you *did* use the install.bat to install the required packages and stuff for the program right?

**Comment by Woisek** [comment] 2023-11-30 12:36
> just for the record, you did use the install.bat to install the required packages and stuff for the program right?

Yes, exactly. Install and then run. Maybe I start over again to test it on the weekend.

But I wonder, if bitsandbytes are a requirement, why aren't they in the requirements_ui.txt? Or at least get installed when needed/required? And also, the selection of an optimizer must not break the whole program. Either remove those that are not compatible or let the requirements for it install via script.

**Comment by Woisek** [comment] 2023-11-30 22:05
> if you look at like 104 of the installer.py file, you can see the subprocess call to install bitsandbytes

But how come that it wasn't installed when I installed the repo then ... ?
I have a RTX 2070 SUPER, so a 'not install' of bitsandbytes should not apply here.

**Comment by Woisek** [comment] 2023-12-01 09:49
> it always installs it, that's the thing.

If it's so, then way does it say otherwise, when you look at the log from 4 days ago I posted?

[...]
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "R:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1012, in
trainer.train(args)
File "R:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 342, in train
optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
File "R:\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3435, in get_optimizer
**raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")**
**ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです**
Failed to train because of error:
Command '['R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe', 'sd_scripts\train_network.py', '--config_file=runtime_store\config.toml', '--dataset_config=runtime_store\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment] 2023-12-02 13:20
> > it always installs it, that's the thing.
> 
> If it's so, then way does it say otherwise, when you look at the log from 4 days ago I posted?
> 
> [...]
> ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "R:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1012, in
> trainer.train(args)
> File "R:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 342, in train
> optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
> File "R:\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3435, in get_optimizer
> **raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")**
> **ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです**
> Failed to train because of error:
> Command '['R:\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe', 'sd_scripts\train_network.py', '--config_file=runtime_store\config.toml', '--dataset_config=runtime_store\dataset.toml']' returned non-zero exit status 1.

That's probably because, for some stupid reason, some very annoying bugs in bitsandbytes code pops up. It's been a long while since this bug popped up, but it might be looking for the bitsandbytes install in your main python, not the venv. I just thought about it a short bit ago, it used to be a very prevalent bug, and it's not something I can predict or fix. I don't even know why it does this, but bitsandbytes doesn't support windows so there's no point in opening an issue with them, they'll just close it.

**Comment by Woisek** [comment] 2023-12-02 16:59
So, basically you say "If you install the repo, it can work or not" ... ?

> but bitsandbytes doesn't support windows

If it doesn't support Windows, then why can it be installed on Windows, and why can other applications use it?
Why do you provide a Windows installation when the repo doesn't work on it?

**Comment by derrian-distro** [comment] 2023-12-02 17:15
> So, basically you say "If you install the repo, it can work or not" ... ?
> 
> > but bitsandbytes doesn't support windows
> 
> If it doesn't support Windows, then why can it be installed on Windows, and why can other applications use it? Why do you provide a Windows installation when the repo doesn't work on it?

because *other* people made it work. this was the case with xformers for a long while too, it's not surprising to me

**Comment by Woisek** [comment] 2023-12-02 23:59
> because _other_ people made it work. this was the case with xformers for a long while too, it's not surprising to me

And why isn't it communicated how those other people made it work? Is this a secret no one shares, or how do we have to take this comment? 🤔

But its okay ... nobody necessarily has to use this repo ... right? 😅

**Comment by Uniter343** [comment] 2024-01-17 04:01
Hi, running into the same issue here. Would be cool if something could be done about it or someone could at least explain how to fix it to me.

**Comment by derrian-distro** [comment] 2024-01-17 23:36
toml errors are pretty much always because of a path, the problem is that the only way to fix it is to just... not use tomls, which I can't really do because kohya likes to use them.

as for the triton error, it's inconsequential, and means exactly nothing on windows.

**Comment by Uniter343** [comment] 2024-01-18 01:45
Ok, thank you for replying. Maybe a warning about the toml errors with possible solutions somewhere would help users. And about the triton errors can't that message just not be displayed on windows devices then?

**Comment by derrian-distro** [comment] 2024-01-18 02:23
the problem with the toml issues is that I don't have concrete solutions, all I can say is to not use characters like ' " and , in your file paths. I don't actually know why it breaks, and since I can't get it to replicate, I can't even debug it

**Comment by Uniter343** [comment] 2024-01-18 02:34
Yeah it was really weird, at first I thought it was because it used / instead of \ everywhere, but that wasn't the problem. For some reason it used double slash (//) in the output dir. And changing that fixed it. (Also I didn't use any of the symbols you mentioned. My paths have spaces but that doesn't seem to cause issues).

**Closed** 2024-02-15 02:42 UTC
